// Generated by scripts/generate-image-manifest.mjs — do not edit by hand.

export const imageDimensions: Record<string, { width: number; height: number }> = {
  "/infographics/infographics_1.jpeg": { width: 1122, height: 1402 },
  "/infographics/infographics_2.jpeg": { width: 1024, height: 1536 },
  "/infographics/infographics_3.jpeg": { width: 1024, height: 1536 },
  "/infographics/infographics_4.jpeg": { width: 1024, height: 1536 },
  "/infographics/infographics_5.jpeg": { width: 1054, height: 1492 },
  "/infographics/infographics_6.jpeg": { width: 1024, height: 1536 },
  "/infographics/infographics_7.jpeg": { width: 1024, height: 1536 },
  "/infographics/infographics_8.jpeg": { width: 1054, height: 1492 },
  "/infographics/infographics_9.jpeg": { width: 1054, height: 1492 },
  "/comics/comics_1.jpeg": { width: 1536, height: 1024 },
  "/comics/comics_2.jpeg": { width: 1536, height: 1024 },
  "/comics/comics_3.jpeg": { width: 1024, height: 1536 },
};

export function getImageDimensions(src: string) {
  return imageDimensions[src] ?? null;
}
